spring.application.name: "agents"

embabel:
  models:
    default-llm: "qwen3:0.6b"

spring:
  ai:
    ollama:
      base-url: "http://localhost:11434"
      chat:
        options:
          model: "qwen3:0.6b"
    mcp:
      client:
        enabled: false
    chat:
      client:
        enabled: false
