spring.application.name: "agents"

embabel:
  models:
    default-llm: "qwen3:0.6b"
    llms:
      embedding: "embeddinggemma:300m-qat-q4_0"
      check: "llama3.2:1b-instruct-q4_K_M"
      first: "qwen3:0.6b"

spring:
  ai:
    ollama:
      base-url: "http://localhost:11434"
      chat:
        options:
          model: "qwen3:0.6b"
          seed: 42               # fixe Zufallszahl f√ºr Reproduzierbarkeit. :contentReference[oaicite:3]{index=3}
    mcp:
      client:
        enabled: false
    chat:
      client:
        enabled: false
